name    'puppet-wordpress'
version '0.0.4'
source 'https://github.com/rcoleman/puppet-wordpress'
author 'jonhadfield/rcoleman'
license 'Apache'
summary 'Puppet module to set up an instance of wordpress, based on work by jonhadfield.'
description 'Installs wordpress and configures an initial site for demonstration purposes. Also allows creation of admin users for the wordpress instance. This was based on work by jonhadfield but the module had drifted quite a bit from his original work. I plan to contact the author and see if a merge makes sense once my development stabilizes.'
project_page 'https://github.com/rcoleman/puppet-wordpress'
